# Generated by Django 4.2 on 2023-06-30 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Email must be at least 6 characters'), django.core.validators.MaxLengthValidator(50, 'Email should not exceed 50 characters')]),
        ),
    ]
